trigger:
  branches:
    include:
    -  master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: Docker@2
  displayName: Docker build and Push
  inputs:
    dockerfile: Dockerfile
    command: buildAndPush
    containerRegistry: 'MyACR'
    repository: my-project-pipeline-environment
    tags: |
      $(Build.BuildNumber)
      latest
